# Configuração de Base de Dados
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/msds_security?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=msds
spring.datasource.password=2diSenai
spring.datasource.driverClassName=org.h2.Driver
# Show SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
app.jwt.secret=ZXhhbXBsb2RlY2hhdmVzZWNyZXRhbG9uZ2Flc2VndXJhY29tdW10YW1hbmhvbWluaW1vZGUyNTZiaXRzZGVzZWd1cmFuY2E=

